version: '3'
services:
  app:
    image: 'laravel-cbr:php8.1-focal-dev'
    build:
      context: ./.docker/app
      dockerfile: Dockerfile
      args:
        WWWGROUP: ${WWWGROUP}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
      - '${HMR_PORT:-8080}:8080'
    environment:
      WWWUSER: ${WWWUSER}
      WWWGROUP: ${WWWGROUP}
      PHP_IDE_CONFIG: serverName=${IDE_SERVER_NAME:-project}
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
      XDEBUG_CLIENT_HOST: ${XDEBUG_CLIENT_HOST:-localhost}
      XDEBUG_CLIENT_PORT: ${XDEBUG_CLIENT_PORT:-9003}
      XDEBUG_IDEKEY: ${XDEBUG_IDEKEY:-""}
      XDEBUG_OUTPUT_DIR: ${XDEBUG_OUTPUT_DIR}
    volumes:
      - '.:/var/www/html'
    networks:
      - laravel-8-cbr
    depends_on:
      - mariadb
      - redis


  mariadb:
    image: 'mariadb:10'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'laravel-8-cbr-mariadb:/var/lib/mysql'
    networks:
      - laravel-8-cbr
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s


  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'laravel-8-cbr-redis:/data'
    networks:
      - laravel-8-cbr
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s


networks:
  laravel-8-cbr:
    driver: bridge


volumes:
  laravel-8-cbr-mariadb:
    driver: local
  laravel-8-cbr-redis:
    driver: local
